/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const DecksidLazyImport = createFileRoute('/decks_id')()
const DecksLazyImport = createFileRoute('/decks')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DecksidLazyRoute = DecksidLazyImport.update({
  path: '/decks_id',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/decks_id.lazy').then((d) => d.Route))

const DecksLazyRoute = DecksLazyImport.update({
  path: '/decks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/decks.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksLazyImport
      parentRoute: typeof rootRoute
    }
    '/decks_id': {
      id: '/decks_id'
      path: '/decks_id'
      fullPath: '/decks_id'
      preLoaderRoute: typeof DecksidLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/decks': typeof DecksLazyRoute
  '/decks_id': typeof DecksidLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/decks': typeof DecksLazyRoute
  '/decks_id': typeof DecksidLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/decks': typeof DecksLazyRoute
  '/decks_id': typeof DecksidLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks' | '/decks_id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks' | '/decks_id'
  id: '__root__' | '/' | '/decks' | '/decks_id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DecksLazyRoute: typeof DecksLazyRoute
  DecksidLazyRoute: typeof DecksidLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DecksLazyRoute: DecksLazyRoute,
  DecksidLazyRoute: DecksidLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/decks",
        "/decks_id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/decks": {
      "filePath": "decks.lazy.tsx"
    },
    "/decks_id": {
      "filePath": "decks_id.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
