/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DecksidImport } from './routes/decks_id'

// Create Virtual Routes

const DecksLazyImport = createFileRoute('/decks')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DecksLazyRoute = DecksLazyImport.update({
  path: '/decks',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/decks.lazy').then((d) => d.Route))

const DecksidRoute = DecksidImport.update({
  path: '/decks_id',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/decks_id': {
      id: '/decks_id'
      path: '/decks_id'
      fullPath: '/decks_id'
      preLoaderRoute: typeof DecksidImport
      parentRoute: typeof rootRoute
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/decks_id': typeof DecksidRoute
  '/decks': typeof DecksLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/decks_id': typeof DecksidRoute
  '/decks': typeof DecksLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/decks_id': typeof DecksidRoute
  '/decks': typeof DecksLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decks_id' | '/decks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decks_id' | '/decks'
  id: '__root__' | '/' | '/decks_id' | '/decks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DecksidRoute: typeof DecksidRoute
  DecksLazyRoute: typeof DecksLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DecksidRoute: DecksidRoute,
  DecksLazyRoute: DecksLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/decks_id",
        "/decks"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/decks_id": {
      "filePath": "decks_id.tsx"
    },
    "/decks": {
      "filePath": "decks.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
